### ISSUE TITLE
Locate in TFS extension

### ISSUE THREAD

**Issue by jawn** [jawn/visualstudio2019-discuss#1]
# Extension homepage

https://marketplace.visualstudio.com/items?itemName=AlexPendleton.LocateinTFS2017

# Issue

- [x] Extension is not available for Visual Studio 2019

**Comment by jawn** [comment]
Upgrade issue logged in extension repo: https://github.com/alexcpendleton/Pendletron.Vsix.LocateInTFS/issues/19

**Comment by alexcpendleton** [comment]
This is now available for 2019 on the VS Marketplace. I'm so grateful for your kind assistance, and thankful for your patience. It did actually work, despite the warning messages for future versions. I'll try to tackle those for next time. Thanks again!

**Comment by jawn** [comment]
Verified in Visual Studio 2019 - works!
